import json
from openai import OpenAI

class AIGuardian:
    def __init__(self, api_key, model="deepseek-chat"):
        self.client = OpenAI(api_key=api_key, base_url="https://api.deepseek.com")
        self.model = model

    def review_signal(self, market_data, technical_signal):
        recent_candles = market_data.tail(5)[['time', 'open', 'high', 'low', 'close', 'adx', 'ema50']].to_string()
        
        prompt = f"""
        Role: Crypto Risk Manager.
        Task: Review a trade signal generated by a technical algorithm.
        
        [Market Context]
        Timeframe: 1H
        Recent Data (Last 5 candles):
        {recent_candles}
        
        [Technical Signal]
        Direction: {technical_signal['signal']}
        Reason: {technical_signal['reason']}
        Current ADX: {market_data.iloc[-1]['adx']:.2f}
        
        [Instruction]
        Analyze the price action and indicators.
        1. If the trend looks exhausted or choppy despite the signal, REJECT it.
        2. If the momentum is strong and clear, APPROVE it.
        
        RETURN JSON ONLY:
        {{
            "approved": true/false,
            "score": 0-100,
            "reason": "Short explanation in Chinese"
        }}
        """

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a strict quantitative trading risk officer. Output JSON only."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.1
            )
            content = response.choices[0].message.content.replace("```json", "").replace("```", "").strip()
            return json.loads(content)
        except Exception as e:
            print(f"[AI Error] {e}")
            return {"approved": False, "score": 0, "reason": f"AI Error: {e}"}
